/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 10 "plugin.go"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/*
返回插件的配置模板，格式为JSON字符串，支持的配置项类型包括：

number: 数值类型，支持min和max属性

switch: 布尔类型，表示开关

string: 字符串类型

具体示例见下方

将会渲染在网页配置页面中
*/
extern char* Plugin_config_template();

/*
插件唯一ID字符串，在配置文件中存储时用于标识插件

例如: lty.go-touch-mapper.default-plugin.v0.0.1
*/
extern char* Plugin_ID();

/*
初始化函数，在插件加载时调用

返回的插件信息字符串数组，将显示在日志中
*/
extern char* Plugin_Init();

// =====================================================================================================
//
extern void Plugin_get_rand_click_target_c(int32_t* inputs_i32, int64_t timestamp, char* config_json, int32_t config_len, int32_t* outputs_i32);
extern void Plugin_get_wheel_move_offset_c(int32_t* inputs_i32, int64_t timestamp, char* config_json, int32_t config_len, int32_t* outputs_i32);

#ifdef __cplusplus
}
#endif
